# Generated by Django 5.0.7 on 2024-07-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
